language: python

# python versions
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "nightly" # problems happen with nightly version

# command to install dependencies
install:
  - make deps
  - pip install coveralls
  - make install

# command to run tests
script:
  - make test-cov

# run after success
after_success:
  - coveralls